#%RAML 1.0
title: age_calculator

/main:
  get:
    responses:
      200:
        body:
          application/json:
            example:
              {
                "result": "Hi kavin your are 23 years old!"
              }